matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      os:
        - linux
        - osx
      env:
        - PIP='sudo pip'
before_install:
  - sudo apt-get update
  - sudo apt install libudev-dev
  - sudo apt install libusb-1.0-0-dev
before_script:
  - npm install
  - git submodule update --remote
  - npm run make-protobuf-files
  - git clone --depth=1 --single-branch --branch develop https://github.com/skycoin/hardware-wallet.git temporalFolder
  - git -C temporalFolder checkout develop
  - git -C temporalFolder submodule init
  - git -C temporalFolder submodule update
  - make clean -C ./temporalFolder
  - make run-emulator -C ./temporalFolder
script:
  - npm run lint
  - npm test
after_script:
  - kill -s KILL $(pgrep emulator)
notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

